---
SettingsSteps:
  #初始化测试环境
  initialize test env:
    control_script: "
    @naboss_page = Watir::Browser.new :chrome;
    "

  #使用测试账户登陆系统
  login with test account:
    control_script: "
    @naboss_page.goto (config.TestEnvParam.URL);
    @naboss_page.text_field(:id, \"email\").set config.TestEnvParam.UserName;
    @naboss_page.text_field(:id, \"password\").set config.TestEnvParam.Password;
    @naboss_page.button(:text,\"登录\").click
    "
    data: config.TestEnvParam.UserName;
    control_recover:

  clean test env:
    control_script: "@naboss_page.li(:id,'closeAllTab').click;clickAlterAccetp(@naboss_page)"